name: Advanced-Deep-Learning-with-Keras
channels:
  - conda-forge
dependencies:
  - python=3.6
  - graphviz
  - h5py
  - keras>=2.0.8
  - matplotlib
  - nb_conda_kernels
  - numpy
  - pandas
  - Pillow
  - pydot
  - scikit-image
  - scipy
  - tensorflow-gpu>=1.3.0
  - pip:
    - gym
